### PR TITLE
add new feature: comparison selector

### PR DESCRIPTION
**Pull request by wwwy3y3**
Hi, 
I implement comparison selector(<,>,<=,>=,!=) for my own need
so you can compile query like `level<=5` now
I also wrote some tests and it works fine

### CODE REVIEW

**Comment by tj** [comment]
cool! just needs style fixes to match the rest of the lib

**Comment by jgallen23** [comment]
bump.  any updates on this?

**Comment by tj** [comment]
close enough :D I'll just patch it up, forgot about this PR

**Comment by jgallen23** [comment]
Thanks TJ

**Comment by tj** [comment]
0.2.0!

**Pull request merged**
